name: 'Zoocha Para Media Text Content'
description: 'Provides Media Text Content component for Zoocha.'
type: 'Feature'

recipes:
  - zr-paragraph-bundle
  - zr-media-bundle

install: 
  - linkit
config:
  strict: false