name: 'Zoocha Para Media Text Content'
description: 'Provides Media Text Content component for Zoocha.'
type: 'Feature'

recipe:
  - zr-paragraph-bundle
  - zr-media-bundle
  - linkit

config:
  strict: false